package com.logicpunch.core

// Auto-generated from docs/cards.json (spec ver 0.7). Do not hand-edit; regenerate instead.
object CardDatabase {
    val allCards: List<Card> = listOf(
        Card(id = "WK-01", theme = "仕事", role = Role.ATTACK, attribute = Attribute.RED, attack = 5000, defense = 1000, combo = 1000, attackText = "それ、会議で言えばいいのでは？", excuseText = "いや、他の業務が急に入ってきて…"),
        Card(id = "WK-02", theme = "仕事", role = Role.ATTACK, attribute = Attribute.BLUE, attack = 5000, defense = 1000, combo = 1000, attackText = "忙しいアピールより手を動かした方が早い", excuseText = "上司の指示が二転三転したので"),
        Card(id = "WK-03", theme = "仕事", role = Role.BALANCE, attribute = Attribute.GREEN, attack = 4000, defense = 4000, combo = 2000, attackText = "まず自分でやってみたら？", excuseText = "そもそも人員が足りていない"),
        Card(id = "WK-04", theme = "仕事", role = Role.BALANCE, attribute = Attribute.RED, attack = 4000, defense = 4000, combo = 2000, attackText = "期限は自分で決めたんですよね", excuseText = "前任者の引き継ぎが雑だったので"),
        Card(id = "WK-05", theme = "仕事", role = Role.DEFENSE, attribute = Attribute.BLUE, attack = 1000, defense = 5000, combo = 1000, attackText = "メールで済む話では？", excuseText = "システムの調子が悪くて"),
        Card(id = "WK-06", theme = "仕事", role = Role.DEFENSE, attribute = Attribute.GREEN, attack = 1000, defense = 5000, combo = 1000, attackText = "できないなら早く言うべきだった", excuseText = "確認待ちで止まっていました"),
        Card(id = "WK-07", theme = "仕事", role = Role.COMBO, attribute = Attribute.RED, attack = 3000, defense = 3000, combo = 3000, attackText = "締切を守れないなら最初から受けなければいい", excuseText = "引き継ぎ資料が無かったので"),
        Card(id = "WK-08", theme = "仕事", role = Role.COMBO, attribute = Attribute.BLUE, attack = 3000, defense = 3000, combo = 3000, attackText = "忙しい忙しい言う人ほど手が遅い", excuseText = "そもそも見積もりが甘かった"),
        Card(id = "LV-01", theme = "恋愛", role = Role.ATTACK, attribute = Attribute.GREEN, attack = 5000, defense = 1000, combo = 1000, attackText = "好きなら素直に連絡すればいい", excuseText = "既読つけると即返信しなきゃいけない空気になるから"),
        Card(id = "LV-02", theme = "恋愛", role = Role.ATTACK, attribute = Attribute.RED, attack = 5000, defense = 1000, combo = 1000, attackText = "好きバレを恐れすぎ", excuseText = "タイミングを見計らってただけ"),
        Card(id = "LV-03", theme = "恋愛", role = Role.BALANCE, attribute = Attribute.BLUE, attack = 4000, defense = 4000, combo = 2000, attackText = "会いたいなら会おうって言えばいい", excuseText = "変に思われたくなかったから"),
        Card(id = "LV-04", theme = "恋愛", role = Role.BALANCE, attribute = Attribute.GREEN, attack = 4000, defense = 4000, combo = 2000, attackText = "デートの日くらい自分で決めて", excuseText = "忙しそうだったから遠慮した"),
        Card(id = "LV-05", theme = "恋愛", role = Role.DEFENSE, attribute = Attribute.RED, attack = 1000, defense = 5000, combo = 1000, attackText = "気になるなら聞けばいいのに", excuseText = "何て返せばいいか分からなかった"),
        Card(id = "LV-06", theme = "恋愛", role = Role.DEFENSE, attribute = Attribute.BLUE, attack = 1000, defense = 5000, combo = 1000, attackText = "既読無視するのは失礼だと思う", excuseText = "本当は考えすぎて送れなかった"),
        Card(id = "LV-07", theme = "恋愛", role = Role.COMBO, attribute = Attribute.GREEN, attack = 3000, defense = 3000, combo = 3000, attackText = "既読つけて既読無視は一番モヤモヤする", excuseText = "気まずくなるのが怖くて"),
        Card(id = "LV-08", theme = "恋愛", role = Role.COMBO, attribute = Attribute.RED, attack = 3000, defense = 3000, combo = 3000, attackText = "好きの反対は無関心、放置は一番の裏切り", excuseText = "相手の気持ちが分からなくて動けなかった"),
        Card(id = "HL-01", theme = "健康", role = Role.ATTACK, attribute = Attribute.BLUE, attack = 5000, defense = 1000, combo = 1000, attackText = "寝ないと治るものも治らない", excuseText = "仕事終わりだと何もする気力が残ってなくて"),
        Card(id = "HL-02", theme = "健康", role = Role.ATTACK, attribute = Attribute.GREEN, attack = 5000, defense = 1000, combo = 1000, attackText = "明日から、は永遠に来ない", excuseText = "分かってるけどやめられないんです"),
        Card(id = "HL-03", theme = "健康", role = Role.BALANCE, attribute = Attribute.RED, attack = 4000, defense = 4000, combo = 2000, attackText = "野菜くらい食べたら？", excuseText = "運動する時間がそもそも無いので"),
        Card(id = "HL-04", theme = "健康", role = Role.BALANCE, attribute = Attribute.BLUE, attack = 4000, defense = 4000, combo = 2000, attackText = "運動不足は自分でも分かってるでしょ", excuseText = "ストレスで暴飲暴食してしまって"),
        Card(id = "HL-05", theme = "健康", role = Role.DEFENSE, attribute = Attribute.GREEN, attack = 1000, defense = 5000, combo = 1000, attackText = "たまには健康診断行ったら？", excuseText = "体質だから仕方ないんです"),
        Card(id = "HL-06", theme = "健康", role = Role.DEFENSE, attribute = Attribute.RED, attack = 1000, defense = 5000, combo = 1000, attackText = "スマホ見すぎで目に悪いよ", excuseText = "明日から本気出す予定でした"),
        Card(id = "HL-07", theme = "健康", role = Role.COMBO, attribute = Attribute.BLUE, attack = 3000, defense = 3000, combo = 3000, attackText = "不摂生の結果を体調のせいにしないで", excuseText = "忙しさを言い訳にしてしまって"),
        Card(id = "HL-08", theme = "健康", role = Role.COMBO, attribute = Attribute.GREEN, attack = 3000, defense = 3000, combo = 3000, attackText = "ジムの会費払うだけで満足してない？", excuseText = "気づいたら三日坊主になってて"),
        Card(id = "MN-01", theme = "お金", role = Role.ATTACK, attribute = Attribute.RED, attack = 5000, defense = 1000, combo = 1000, attackText = "欲しいものより必要なものを買ったら？", excuseText = "セールでどうしても買っちゃって"),
        Card(id = "MN-02", theme = "お金", role = Role.ATTACK, attribute = Attribute.BLUE, attack = 5000, defense = 1000, combo = 1000, attackText = "収入が増えても支出が増えたら一緒", excuseText = "付き合いでどうしても出費がかさんで"),
        Card(id = "MN-03", theme = "お金", role = Role.BALANCE, attribute = Attribute.GREEN, attack = 4000, defense = 4000, combo = 2000, attackText = "家計簿つければ無駄遣い分かるよ", excuseText = "急な出費が続いただけです"),
        Card(id = "MN-04", theme = "お金", role = Role.BALANCE, attribute = Attribute.RED, attack = 4000, defense = 4000, combo = 2000, attackText = "サブスク解約すればいいのでは", excuseText = "自分へのご褒美です"),
        Card(id = "MN-05", theme = "お金", role = Role.DEFENSE, attribute = Attribute.BLUE, attack = 1000, defense = 5000, combo = 1000, attackText = "その出費、本当に必要だった？", excuseText = "将来のための自己投資なので"),
        Card(id = "MN-06", theme = "お金", role = Role.DEFENSE, attribute = Attribute.GREEN, attack = 1000, defense = 5000, combo = 1000, attackText = "貯金は先に取り分けるものだよ", excuseText = "気づいたらポチッてました"),
        Card(id = "MN-07", theme = "お金", role = Role.COMBO, attribute = Attribute.RED, attack = 3000, defense = 3000, combo = 3000, attackText = "ボーナス入っても使い切るなら意味ない", excuseText = "気が大きくなってしまって"),
        Card(id = "MN-08", theme = "お金", role = Role.COMBO, attribute = Attribute.BLUE, attack = 3000, defense = 3000, combo = 3000, attackText = "「安いから買う」が一番高くつく", excuseText = "限定と言われると弱くて"),
        Card(id = "RL-01", theme = "人間関係", role = Role.ATTACK, attribute = Attribute.GREEN, attack = 5000, defense = 1000, combo = 1000, attackText = "言いたいことがあるならはっきり言えばいい", excuseText = "場の空気を悪くしたくなかったので"),
        Card(id = "RL-02", theme = "人間関係", role = Role.ATTACK, attribute = Attribute.RED, attack = 5000, defense = 1000, combo = 1000, attackText = "関係を壊したくないなら、まず本音で話すべき", excuseText = "言ってもどうせ変わらないと思って"),
        Card(id = "RL-03", theme = "人間関係", role = Role.BALANCE, attribute = Attribute.BLUE, attack = 4000, defense = 4000, combo = 2000, attackText = "誘われたくないなら断ればいい", excuseText = "嫌われるのが怖くて言えなかった"),
        Card(id = "RL-04", theme = "人間関係", role = Role.BALANCE, attribute = Attribute.GREEN, attack = 4000, defense = 4000, combo = 2000, attackText = "陰で言うくらいなら本人に言ったら", excuseText = "昔からの付き合いだから今更言えない"),
        Card(id = "RL-05", theme = "人間関係", role = Role.DEFENSE, attribute = Attribute.RED, attack = 1000, defense = 5000, combo = 1000, attackText = "苦手な人とは距離を置けばいい", excuseText = "その場では言葉が出てこなくて"),
        Card(id = "RL-06", theme = "人間関係", role = Role.DEFENSE, attribute = Attribute.BLUE, attack = 1000, defense = 5000, combo = 1000, attackText = "空気読むより言葉で伝えた方が早い", excuseText = "後で言おうと思っているうちに時間が経って"),
        Card(id = "RL-07", theme = "人間関係", role = Role.COMBO, attribute = Attribute.GREEN, attack = 3000, defense = 3000, combo = 3000, attackText = "我慢して付き合うのは優しさじゃなくて逃げ", excuseText = "関係を壊すのが怖くて"),
        Card(id = "RL-08", theme = "人間関係", role = Role.COMBO, attribute = Attribute.RED, attack = 3000, defense = 3000, combo = 3000, attackText = "察してほしいはただの甘え", excuseText = "うまく言葉にできなくて"),
    )
}
